let q1 = document.querySelector('#q1')
let lg = document.querySelectorAll('.lg')
let lg2 = document.querySelectorAll('.lg2')
let content = document.querySelectorAll('.content')
lg[0].addEventListener('click', () => {
    content[0].classList.remove('content2')
    lg[0].classList.add('lgaft')
    lg2[0].classList.add('lgaft2')
})
lg[1].addEventListener('click', () => {
    lg2[0].classList.remove('lgaft2')
    lg[0].classList.remove('lgaft')
    content[0].classList.add('content2')
    content[1].classList.remove('content2')
    lg[1].classList.add('lgaft')
    lg2[1].classList.add('lgaft2')
})
lg[2].addEventListener('click', () => {
    lg2[0].classList.remove('lgaft2')
    lg2[1 
    ].classList.remove('lgaft2')
    lg[0].classList.remove('lgaft')
    lg[1].classList.remove('lgaft')
    content[0].classList.add('content2')
    content[1].classList.add('content2')
    content[2].classList.remove('content2')
    lg[2].classList.add('lgaft')
    lg2[2].classList.add('lgaft2')
})
lg2[0].addEventListener('click', () => {
    content[0].classList.add('content2')
    lg[0].classList.remove('lgaft')
    lg2[0].classList.remove('lgaft2')
})
lg2[1].addEventListener('click', () => {
    content[1].classList.add('content2')
    lg[1].classList.remove('lgaft')
    lg2[1].classList.remove('lgaft2')
})
lg2[2].addEventListener('click', () => {
    content[2].classList.add('content2')
    lg[2].classList.remove('lgaft')
    lg2[2].classList.remove('lgaft2')
})